In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Bakery_1.csv")

In [3]:
df

       TransactionNo          Items             DateTime    Daypart  DayType
0                  1          Bread  2016-10-30 09:58:11    Morning  Weekend
1                  2   Scandinavian  2016-10-30 10:05:34    Morning  Weekend
2                  2   Scandinavian  2016-10-30 10:05:34    Morning  Weekend
3                  3  Hot chocolate  2016-10-30 10:07:57    Morning  Weekend
4                  3            Jam  2016-10-30 10:07:57    Morning  Weekend
...              ...            ...                  ...        ...      ...
20502           9682         Coffee  2017-09-04 14:32:58  Afternoon  Weekend
20503           9682            Tea  2017-09-04 14:32:58  Afternoon  Weekend
20504           9683         Coffee  2017-09-04 14:57:06  Afternoon  Weekend
20505           9683         Pastry  2017-09-04 14:57:06  Afternoon  Weekend
20506           9684      Smoothies  2017-09-04 15:04:24  Afternoon  Weekend

[20507 rows x 5 columns]

In [4]:
from mlxtend.frequent_patterns import apriori, association_rules

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20507 entries, 0 to 20506
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TransactionNo  20507 non-null  int64
 1   Items          20507 non-null  object
 2   DateTime       20507 non-null  object
 3   Daypart        20507 non-null  object
 4   DayType        20507 non-null  object
dtypes: int64(1), object(4)
memory usage: 801.2+ KB

In [6]:
df.describe()

       TransactionNo
count   20507.000000
mean     4976.202370
std      2796.203001
min         1.000000
25%      2552.000000
50%      5137.000000
75%      7357.000000
max      9684.000000

In [7]:
df['Items'].nunique()

94

In [8]:
basket = (df.groupby(['TransactionNo', 'Items'])['Items']
            .count().unstack().reset_index().fillna(0)
            .set_index('TransactionNo'))

In [9]:
basket = basket.applymap(lambda x: 1 if x > 0 else 0)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8336\3498954818.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  basket = basket.applymap(lambda x: 1 if x > 0 else 0)

In [10]:
frequent_itemsets = apriori(basket, min_support=0.01, use_colnames=True)

C:\Users\Lenovo\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [11]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

In [15]:
rules = rules.sort_values(by="confidence","lift", ascending=[False,False])

In [16]:
print(rules.head(10))

        antecedents consequents  antecedent support  consequent support  \
19          (Toast)    (Coffee)            0.033597            0.478394
12      (Medialuna)    (Coffee)            0.061807            0.478394
14         (Pastry)    (Coffee)            0.086107            0.478394
10          (Juice)    (Coffee)            0.038563            0.478394
16       (Sandwich)    (Coffee)            0.071844            0.478394
3            (Cake)    (Coffee)            0.103856            0.478394
6         (Cookies)    (Coffee)            0.054411            0.478394
8   (Hot chocolate)    (Coffee)            0.058320            0.478394
0          (Pastry)     (Bread)            0.086107            0.327205
4            (Cake)       (Tea)            0.103856            0.142631

     support  confidence      lift  representativity  leverage  conviction  \
19  0.023666    0.704403  1.472431               1.0  0.007593    1.764582
12  0.035182    0.569231  1.189878               1.0  0.005614    1.210871
14  0.047544    0.552147  1.154168               1.0  0.006351    1.164682
10  0.020602    0.534247  1.116750               1.0  0.002154    1.119919
16  0.038246    0.532353  1.112792               1.0  0.003877    1.115384
3   0.054728    0.526958  1.101515               1.0  0.005044    1.102664
6   0.028209    0.518447  1.083723               1.0  0.002179    1.083174
8   0.029583    0.507246  1.060311               1.0  0.001683    1.058553
0   0.029160    0.338650  1.034977               1.0  0.000985    1.017305
4   0.023772    0.228891  1.604781               1.0  0.008959    1.111865

    zhangs_metric   jaccard  certainty  kulczynski
19       0.332006  0.048464   0.433293    0.376936
12       0.170091  0.069665   0.174148    0.321387
14       0.146161  0.091968   0.141396    0.325764
10       0.108738  0.041507   0.107078    0.288656
16       0.109205  0.074701   0.103448    0.306150
3        0.102840  0.103745   0.093105    0.320679
6        0.081700  0.055905   0.076787    0.288707
8        0.060403  0.058333   0.055314    0.284542
0        0.036980  0.075908   0.017011    0.213884
4        0.420538  0.106736   0.100611    0.197779

In [17]:
df['Context'] = df['Daypart'] + "_" + df['DayType']

In [18]:
basket = (df.groupby(['TransactionNo', 'Context'])['Items']
            .apply(list)
            .reset_index())

In [19]:
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_ary = te.fit(basket['Items']).transform(basket['Items'])
item_matrix = pd.DataFrame(te_ary, columns=te.columns_)

In [20]:
item_matrix['Context'] = basket['Context']

In [21]:
rules_list = []

for context in item_matrix['Context'].unique():
    sub_matrix = item_matrix[item_matrix['Context'] == context].drop(columns=['Context'])
    
    
    frequent_items = apriori(sub_matrix, min_support=0.02, use_colnames=True)
    

    rules = association_rules(frequent_items, metric="lift", min_threshold=1.0)
    rules['Context'] = context
    rules_list.append(rules)

In [34]:
all_rules = pd.concat(rules_list, ignore_index=True)


all_rules = all_rules.sort_values(by=['Context','confidence'], ascending=[True, False])

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8336\293120780.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_rules = pd.concat(rules_list, ignore_index=True)

In [35]:
pd.set_option("display.max_rows", 20)
print(all_rules[['antecedents','consequents','support','confidence','lift','Context']])

         antecedents      consequents   support  confidence      lift  \
66          (Pastry)         (Coffee)  0.025263    0.531646  1.160684
61            (Cake)         (Coffee)  0.066165    0.527578  1.151803
58       (Alfajores)         (Coffee)  0.021053    0.518519  1.132025
68        (Sandwich)         (Coffee)  0.061353    0.511278  1.116218
64   (Hot chocolate)         (Coffee)  0.027970    0.508197  1.109491
..               ...              ...       ...         ...       ...
9           (Coffee)          (Juice)  0.023368    0.047820  1.419960
5           (Coffee)        (Cookies)  0.022680    0.046414  1.274182
13          (Coffee)         (Muffin)  0.021993    0.045007  1.023207
136  (Mineral water)          (Juice)  0.333333    1.000000  3.000000
137          (Juice)  (Mineral water)  0.333333    1.000000  3.000000

               Context
66   Afternoon_Weekday
61   Afternoon_Weekday
58   Afternoon_Weekday
68   Afternoon_Weekday
64   Afternoon_Weekday
..                 ...
9      Morning_Weekend
5      Morning_Weekend
13     Morning_Weekend
136      Night_Weekday
137      Night_Weekday

[138 rows x 6 columns]